### ISSUE TITLE
Screenshots for all resolutions 

### ISSUE THREAD

**Issue by serejahh** [gromadco/Talking-Companion-iOS#58]
@serejahh:
- [x] make screenshots for each resolution\device

@betula-pendula 
add more screenshots similar to ones at http://www.gromad.co/Talking-Companion-iOS/ 
- [x] 4.7"
- [x] 5.5"
- [x] 4"
- [x] 3.5"
- [x] iPad

Russian screenshots
- [x] 4.7" 
- [x] 5.5"
- [x] 4"
- [ ] 3.5"
- [x] iPad

**Comment by betula-pendula** [comment]
![1136x640-cafe-en](https://cloud.githubusercontent.com/assets/8578505/5593275/01cebec4-920c-11e4-861f-d7b7fc55fd98.jpg)
![1136x640-gas-en](https://cloud.githubusercontent.com/assets/8578505/5593279/01cf9d80-920c-11e4-9fbc-77f9cf1f1e6e.jpg)
![1136x640-tower-en](https://cloud.githubusercontent.com/assets/8578505/5593276/01cf2b52-920c-11e4-9f00-ddeb3f7ff74b.jpg)
![2208x1242-cafe-en](https://cloud.githubusercontent.com/assets/8578505/5593278/01cf4452-920c-11e4-8f0b-6d152ee48f19.jpg)
![2208x1242-gas-en](https://cloud.githubusercontent.com/assets/8578505/5593280/01d05d92-920c-11e4-966f-00bff5b95337.jpg)
![2208x1242-tower-en](https://cloud.githubusercontent.com/assets/8578505/5593277/01cf43a8-920c-11e4-8db1-fd4e703cf5ed.jpg)

**Comment by betula-pendula** [comment]
![960x640-cafe-ru](https://cloud.githubusercontent.com/assets/8578505/5593282/23aa64b2-920c-11e4-8f30-6b3a0cc30e56.jpg)
![960x640-gas-ru](https://cloud.githubusercontent.com/assets/8578505/5593281/23aa65de-920c-11e4-91f0-c4bdb77d932d.jpg)
![960x640-tower-ru](https://cloud.githubusercontent.com/assets/8578505/5593284/23ad0d52-920c-11e4-8cb4-8d2588cd9934.jpg)
![1136x640-cafe-ru](https://cloud.githubusercontent.com/assets/8578505/5593286/23af43ce-920c-11e4-97f5-364154d3659f.jpg)
![1136x640-gas-ru](https://cloud.githubusercontent.com/assets/8578505/5593283/23aa6cb4-920c-11e4-9949-41864d9dbe87.jpg)
![1136x640-tower-ru](https://cloud.githubusercontent.com/assets/8578505/5593285/23ae6440-920c-11e4-95b5-ade1c80b11b2.jpg)
![1334x750-cafe-ru](https://cloud.githubusercontent.com/assets/8578505/5593287/23c8bd18-920c-11e4-86b6-875afde4bd44.jpg)
![1334x750-gas-ru](https://cloud.githubusercontent.com/assets/8578505/5593289/23c99ada-920c-11e4-8e3c-6674bcc1f18f.jpg)
![1334x750-tower-ru](https://cloud.githubusercontent.com/assets/8578505/5593288/23c8d9a6-920c-11e4-87da-92a48f380726.jpg)
![2048x1536-ipad-cafe-ru](https://cloud.githubusercontent.com/assets/8578505/5593290/23cb2f26-920c-11e4-8e21-c5ee0fc18215.jpg)
![2048x1536-ipad-gas-ru](https://cloud.githubusercontent.com/assets/8578505/5593292/23cdb566-920c-11e4-8d2b-cd62da8f668b.jpg)
![2048x1536-ipad-tower-ru](https://cloud.githubusercontent.com/assets/8578505/5593291/23cc85ec-920c-11e4-9a06-bbe84f0fd608.jpg)
![2208x1242-cafe-ru](https://cloud.githubusercontent.com/assets/8578505/5593294/23e72474-920c-11e4-940a-3da637ad6fd4.jpg)
![2208x1242-gas-ru](https://cloud.githubusercontent.com/assets/8578505/5593293/23e660de-920c-11e4-8d03-93fe6fb62b45.jpg)
![2208x1242-tower-ru](https://cloud.githubusercontent.com/assets/8578505/5593295/23eb6c1e-920c-11e4-8009-a3caf00cacf1.jpg)

**Comment by betula-pendula** [comment]
![960x640-cafe-ru](https://cloud.githubusercontent.com/assets/8578505/5596844/5ced82a6-92a0-11e4-8991-73a388b9caec.jpg)
![960x640-gas-ru](https://cloud.githubusercontent.com/assets/8578505/5596845/5cedb8fc-92a0-11e4-9c68-37ed68bf88e4.jpg)
![960x640-tower-ru](https://cloud.githubusercontent.com/assets/8578505/5596846/5ceee056-92a0-11e4-99fc-8ee04fc0e56b.jpg)
